export default {
  CACHE_RESULTS: 'CACHE_RESULTS',
  REQUEST_CACHED_RESULTS: 'REQUEST_CACHED_RESULTS',
  REQUEST_ENVIRONMENT: 'REQUEST_ENVIRONMENT',
  REQUEST_HOST: 'REQUEST_HOST',
  REQUEST_PERSON_ID: 'REQUEST_PERSON_ID',
  REQUEST_SESSION_ID: 'REQUEST_SESSION_ID',
  SET_ENVIRONMENT: 'SET_ENVIRONMENT',
  SET_HOST: 'SET_HOST',
  SET_PERSON_ID: 'SET_PERSON_ID',
  SET_SESSION_ID: 'SET_SESSION_ID'
}
