export default {
  CACHE_RESULTS: 'CACHE_RESULTS',
  CLEAR_RESULTS_CACHE: 'CLEAR_RESULTS_CACHE',
  MARK_RESULT_COMPLETE: 'MARK_RESULT_COMPLETE',
  MARK_RESULT_INCOMPLETE: 'MARK_RESULT_INCOMPLETE',
  REQUEST_CACHED_RESULTS: 'REQUEST_CACHED_RESULTS',
  REQUEST_COMPLETED_RESULTS: 'REQUEST_COMPLETED_RESULTS',
  REQUEST_ENVIRONMENT: 'REQUEST_ENVIRONMENT',
  REQUEST_HOST: 'REQUEST_HOST',
  REQUEST_PERSON_ID: 'REQUEST_PERSON_ID',
  REQUEST_SESSION_ID: 'REQUEST_SESSION_ID',
  SET_ENVIRONMENT: 'SET_ENVIRONMENT',
  SET_HOST: 'SET_HOST',
  SET_PERSON_ID: 'SET_PERSON_ID',
  SET_SESSION_ID: 'SET_SESSION_ID'
}
